//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab16
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbDocEntities : DbContext
    {
        public DbDocEntities()
            : base("name=DbDocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TGranter> Granter { get; set; }
        public virtual DbSet<TGranterReceipt> GranterReceipt { get; set; }
        public virtual DbSet<TReceipt> Receipt { get; set; }
    }
}
