//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab16
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGranterReceipt
    {
        public int Id { get; set; }
        public int Receipt_id { get; set; }
        public int Granter_id { get; set; }
    
        public virtual TGranter TGranter { get; set; }
        public virtual TReceipt TReceipt { get; set; }
    }
}
